config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get 'about' => 'pages#about'
  get 'story' => 'pages#story'

  mount Commontator::Engine => '/commontator'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	validates :image, presence: true
    validates :description, presence: true

    acts_as_commontable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true

  acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def story
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  def show
    commontator_thread_show(@pin)
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/commontator/comments/_actions.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% can_edit = comment.can_be_edited_by?(user)
   can_delete = comment.can_be_deleted_by?(user) %>

<% if can_edit %>
  <%= link_to t('commontator.comment.actions.edit'),
              commontator.edit_comment_path(comment),
              :id => "comment_#{comment.id.to_s}_edit_link",
              :class => "comment_edit_link",
              :remote => true %>
<% end %>

&nbsp;

<% if can_delete %>
  <% is_deleted = comment.is_deleted? %>
  <% del_string = is_deleted ? 'undelete' : 'delete' %>
  <%= link_to t("commontator.comment.actions.#{del_string}"),
              commontator.polymorphic_path([del_string, comment]),
              :confirm => (!is_deleted ? t('commontator.comment.actions.confirm_delete') : nil),
              :method => :put,
              :id => "comment_#{comment.id.to_s}_#{del_string}_link",
              :class => "comment_#{del_string}_link",
              :remote => true %>
<% end %>

app/views/commontator/comments/_body.html.erb
<% # Clients of this partial must provide the following variable:
   # comment
%>

<%= simple_format comment.is_deleted? ? \
      t('commontator.comment.status.deleted_by',
        :deleter_name => Commontator.commontator_name(comment.editor)) : \
      comment.body %>

app/views/commontator/comments/_form.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   #
   # Optionally, they can also supply the following variables:
   per_page ||= nil
   thread ||= nil
   no_remote ||= false
%>

<% config = comment.thread.config %>

<% if comment.errors.any? %>
  <div class="comment_error_explanation">
    <h3><%= t "commontator.comment.errors.#{comment.id.blank? ? 'create' : 'update'}" %></h3>

    <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([commontator, thread, comment],
             :remote => !no_remote) do |f| %>

  <%= hidden_field_tag :per_page, per_page %>
  
  <div class="comment_form_field">
    <%= f.text_area :body, :rows => '7' %>
    <%= javascript_tag('Commontator.initMentions()') if Commontator.mentions_enabled %>
  </div>
  
  <div class="comment_form_actions">
    <%= f.submit t("commontator.comment.actions.#{comment.id.blank? ? 'create' : 'update'}") %>
    <%= f.submit t('commontator.comment.actions.cancel'), :name => 'cancel' %>
  </div>
  
<% end %>

app/views/commontator/comments/_list.html.erb
<% # Clients of this partial must supply the following variables:
   # comments
   # user
%>

<% comments.includes(:creator, :editor).each do |comment| %>
  <%= render :partial => 'commontator/comments/show',
             :locals => { :comment => comment,
                          :user => user } %>
<% end %>

app/views/commontator/comments/_show.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% creator = comment.creator
   name = Commontator.commontator_name(creator) || ''
   link = Commontator.commontator_link(creator, main_app) || ''
   avatar = Commontator.commontator_avatar(creator, self) || ''
%>

<div id="comment_<%= comment.id.to_s %>_div" class="comment">
  <div id="comment_<%= comment.id.to_s %>_top_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_commontator_span" class="comment_commontator">
      <%= link.blank? ? name : link_to(name, link) %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_actions_span" class="comment_actions">
      <%= render :partial => 'commontator/comments/actions',
                 :locals => { :comment => comment,
                              :user => user } %>
    </span>
  </div>
  <div id="comment_<%= comment.id.to_s %>_middle_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_avatar_span" class="comment_avatar">
      <%= avatar %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_votes_span" class="comment_votes">
      <%= render :partial => 'commontator/comments/votes',
                 :locals => { :comment => comment,
                              :user => user } %>
    </span>
    <div id="comment_<%= comment.id.to_s %>_body_div" class="comment_body">
      <%= render :partial => 'commontator/comments/body',
                 :locals => { :comment => comment } %>
    </div>
  </div>
  <div id="comment_<%= comment.id.to_s %>_bottom_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_created_timestamp_span" class="comment_timestamp">
      <%= comment.created_timestamp %>
    </span>
    <br/>
    <span id="comment_<%= comment.id.to_s %>_updated_timestamp_span" class="comment_timestamp">
    <% if comment.is_modified? %>
      <%= comment.updated_timestamp %>
    <% end %>
    </span>
  </div>
</div>

app/views/commontator/comments/_votes.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   # user
%>

<% if comment.can_be_voted_on? %>
  <% can_vote = comment.can_be_voted_on_by?(user) %>
  <% vote = comment.get_vote_by(user) %>
  <% comment_voting = comment.thread.config.comment_voting.to_sym %>

  <% if comment_voting == :ld || comment_voting == :l %>
  <% vtype = (comment_voting == :ld) ? 'upvote' : 'like' %>
  <span id="comment_<%= comment.id %>_<%= vtype %>_span"
        class="comment_<%= vtype %>">
    <% if can_vote && (vote.blank? || !vote.vote_flag) %>
      <%= form_tag commontator.upvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/upvote.png",
              :onmouseover => "this.src='#{image_path("commontator/upvote_hover.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/upvote.png")}'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/upvote_active.png",
              :onmouseover => "this.src='#{image_path("commontator/upvote.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/upvote_active.png")}'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/upvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>

  <span id="comment_<%= comment.id %>_vote_count_span" class="comment_vote_count">
    <% config = comment.thread.config %>
    <%= config.vote_count_proc.call(comment.thread,
          comment.get_upvotes.size, comment.get_downvotes.size) %>
  </span>

  <% if comment_voting == :ld %>
  <span id="comment_<%= comment.id %>_downvote_span" class="comment_downvote">
    <% if can_vote && (vote.blank? || vote.vote_flag) %>
      <%= form_tag commontator.downvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/downvote.png",
              :onmouseover => "this.src='#{image_path("commontator/downvote_hover.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/downvote.png")}'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/downvote_active.png",
              :onmouseover => "this.src='#{image_path("commontator/downvote.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/downvote_active.png")}'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/downvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>
<% end %>

app/views/commontator/comments/cancel.js.erb
<% unless @comment.try(:id).blank? %>
  <% @comment.reload %>
  $("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
    render :partial => 'body', :locals => { :comment => @comment }) %>");
<% end %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render :partial => 'form',
           :locals => { :comment => @new_comment,
                        :thread => @thread,
                        :per_page => @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

<%= javascript_proc %>

app/views/commontator/comments/create.js.erb
<%= render :partial => 'commontator/threads/show',
           :locals => { :thread => @thread,
                        :user => @user,
                        :page => @thread.new_comment_page(@per_page),
                        :per_page => @per_page } %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render :partial => 'form',
           :locals => { :comment => @new_comment,
                        :thread => @thread,
                        :per_page => @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

$("#comment_<%= @comment.id.to_s %>_div").hide().fadeIn()[0].scrollIntoView();

<%= javascript_proc %>

app/views/commontator/comments/delete.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'body', :locals => { :comment => @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");
                                                           
$("#comment_<%= @comment.id.to_s %>_actions_span").html("<%= escape_javascript(
  render :partial => 'actions',
         :locals => { :comment => @comment,
                      :user => @user }) %>");
         
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render :partial => 'votes',
         :locals => { :comment => @comment,
                      :user => @user }) %>");

$("#comment_<%= @comment.id.to_s %>_div").hide();


<%= javascript_proc %>

app/views/commontator/comments/edit.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'form',
         :locals => { :comment => @comment }) %>");
         
<%= javascript_proc %>

app/views/commontator/comments/new.js.erb
$("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
  render :partial => 'form',
         :locals => { :comment => @comment,
                      :thread => @thread,
                      :per_page => @per_page }) %>");

$("#thread_<%= @thread.id %>_new_comment_form_div").fadeIn()[0].scrollIntoView();

$("#thread_<%= @thread.id %>_new_comment_link_div").hide();

<%= javascript_proc %>

app/views/commontator/comments/update.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'body', :locals => { :comment => @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");

<%= javascript_proc %>

app/views/commontator/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render :partial => 'votes',
         :locals => { :comment => @comment,
                      :user => @user }) %>");

<%= javascript_proc %>

app/views/commontator/shared/_thread.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% if thread.can_be_read_by?(user) %>
  <div id="thread_<%= thread.id %>_div" class="thread" style="display: none;">
    <% if @commontator_thread_show %>
      <%= render :partial => 'commontator/threads/show',
                 :locals => { :thread => thread,
                              :user => user,
                              :page => @commontator_page,
                              :per_page => @commontator_per_page } %>
    <% else %>
      <% subscription = thread.subscription_for(user) %>
      <%= link_to "#{t 'commontator.thread.actions.show'} (#{(subscription.unread_comments.count.to_s + '/') if subscription}#{thread.filtered_comments.count.to_s})",
                  commontator.thread_path(thread),
                  :remote => true %>
    <% end %>
  </div>
<% end %>

app/views/commontator/subscriptions/_link.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% is_subscribed = !!thread.subscription_for(user) %>
<% sub_string = is_subscribed ? "unsubscribe" : "subscribe" %>
<%= link_to t("commontator.subscription.actions.#{sub_string}"),
            commontator.polymorphic_path([sub_string, thread]),
            :confirm => (is_subscribed ? t('commontator.subscription.actions.confirm_unsubscribe') : \
                          nil),
            :method => :put,
            :id => "thread_#{thread.id.to_s}_#{sub_string}_link",
            :class => "thread_#{sub_string}_link",
            :remote => true %>

app/views/commontator/subscriptions/subscribe.js.erb
$("#thread_<%= @thread.id.to_s %>_subscription_span").html("<%= escape_javascript(
  render :partial => 'link',
         :locals => { :thread => @thread,
                      :user => @user }) %>");

<%= javascript_proc %>

app/views/commontator/threads/_hide_show_links.js.erb
<% # Clients of this partial must supply the following variables:
   # thread
%>

$("#thread_<%= thread.id %>_hide_link").click(function() {
  $("#thread_<%= thread.id %>_span").hide();

  $("#thread_<%= thread.id %>_show_span").fadeIn()[0].scrollIntoView();
});

$("#thread_<%= thread.id %>_show_link").click(function() {
  $("#thread_<%= thread.id %>_span").fadeIn()[0].scrollIntoView();

  $("#thread_<%= thread.id %>_show_span").hide();
});

$("#thread_<%= thread.id %>_hide_span").show();

app/views/commontator/threads/_reply.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
   # per_page

   hidden_class = @new_comment.nil? ? ' commontator_hidden' : '' %>

<div id="thread_<%= thread.id %>_reply" class="thread_reply">
  <% if thread.is_closed? %>
    <p><%= t 'commontator.thread.status.cannot_post' %></p>
  <% elsif !user %>
    <p><%= t 'commontator.require_login' %>.</p>
  <% else %>
    <div id="thread_<%= thread.id %>_new_comment_form_div" class="thread_new_comment_form<%=
    hidden_class %>">
      <% unless @new_comment.nil? %>
        <%= render :partial => 'commontator/comments/form',
                   :locals => { :comment => @new_comment,
                                :thread => thread,
                                :per_page => per_page } %>
      <% end %>
    </div>

    <% if @new_comment.nil? %>
      <div id="thread_<%= thread.id %>_new_comment_link_div" class="thread_new_comment_link">
        <%= link_to t('commontator.comment.actions.new'),
            commontator.new_thread_comment_path(thread, :per_page => per_page),
            :remote => true %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/commontator/threads/_show.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
   # page
   # per_page
   # Optionally, they can also supply the following variable:
   show_all ||= false
%>

<% can_subscribe = thread.can_subscribe?(user)
   can_edit = thread.can_be_edited_by?(user) %>

<span id="thread_<%= thread.id.to_s %>_show_span" class="thread_show commontator_hidden">
  <%= link_to t('commontator.thread.actions.show'),
              '#',
              id: "thread_#{thread.id.to_s}_show_link",
              class: "thread_show_link" %>
</span>

<span id="thread_<%= thread.id %>_span" class="thread_span">
  <span id="thread_<%= thread.id.to_s %>_actions_span" class="thread_actions">
    <span id="thread_<%= thread.id.to_s %>_hide_span" class="thread_hide commontator_hidden">
      <%= link_to t('commontator.thread.actions.hide'),
                  '#',
                  id: "thread_#{thread.id.to_s}_hide_link",
                  class: "thread_hide_link" %>
    </span>

    &nbsp;

    <% if can_subscribe %>
      <span id="thread_<%= thread.id.to_s %>_subscription_span" class="thread_subscription">
        <%= render :partial => 'commontator/subscriptions/link',
                   :locals => { :thread => thread,
                                :user => user } %>
      </span>
    <% end %>

    &nbsp;

    <% if can_edit %>
      <% filter_string = show_all ? 'filter' : 'show_all'
         is_closed = thread.is_closed?
         close_string = is_closed ? 'reopen' : 'close' %>

      <% if thread.is_filtered? %>
        <%= link_to t("commontator.thread.actions.#{filter_string}"),
                    commontator.thread_path(thread, :show_all => (show_all ? nil : true)),
                    :id => "thread_#{thread.id.to_s}_#{filter_string}_link",
                    :class => "thread_#{filter_string}_link",
                    :remote => true %>

        &nbsp;
      <% end %>

      <%= link_to t("commontator.thread.actions.#{close_string}"),
                  commontator.polymorphic_path([close_string, thread]),
                  :confirm => (!is_closed ? t('commontator.thread.actions.confirm_close') : nil),
                  :method => :put,
                  :id => "thread_#{thread.id.to_s}_#{close_string}_link",
                  :class => "thread_#{close_string}_link",
                  :remote => true %>
    <% end %>
  </span>

  <span id="thread_<%= thread.id.to_s %>_header_span" class="thread_header">
    <%= t "commontator.thread.status.#{thread.is_closed? ? 'closed' : 'open'}",
          :closer_name => (thread.is_closed? ? Commontator.commontator_name(thread.closer) : '') %>
  </span>

  <% if thread.config.comment_order == :l %>
    <%= render :partial => 'commontator/threads/reply',
               :locals => { :thread => thread, :user => user, :per_page => per_page } %>
  <% end %>

  <div id="thread_<%= thread.id.to_s %>_comment_list_div" class="thread_comment_list">
    <% comments = show_all ? thread.ordered_comments(true) : \
                             thread.paginated_comments(page, per_page) %>
    <%= render :partial => 'commontator/comments/list',
               :locals => { :comments => comments,
                            :user => user } %>
  </div>

  <% if thread.will_paginate? && !show_all %>
    <div id="thread_<%= thread.id.to_s %>_pagination_div" class="thread_pagination">
      <div id="thread_<%= thread.id.to_s %>_page_entries_info_div" class="thread_page_entries_info">
        <%= page_entries_info comments,
                              :params => { :controller => 'commontator/threads',
                                           :action => 'show',
                                           :id => thread.id,
                                           :page => page,
                                           :per_page => per_page } %>.
      </div>

      <div id="thread_<%= thread.id.to_s %>_will_paginate_div" class="thread_will_paginate">
        <%= will_paginate comments,
                          :renderer => Commontator::LinkRenderer,
                          :routes_proxy => commontator,
                          :remote => true,
                          :params => { :controller => 'commontator/threads',
                                       :action => 'show',
                                       :id => thread.id,
                                       :page => page,
                                       :per_page => per_page } %>
      </div>
    </div>
  <% end %>

  <% if thread.config.comment_order != :l %>
    <%= render :partial => 'commontator/threads/reply',
               :locals => { :thread => thread, :user => user, :per_page => per_page } %>
  <% end %>
</span>

<script type="text/javascript">
  <%= render partial: 'commontator/threads/hide_show_links.js',
             locals: { thread: thread } %>
</script>

app/views/commontator/threads/_show.js.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
   # page
   # per_page
   # Optionally, they can also supply the following variable:
   show_all ||= false
%>

$("#thread_<%= thread.id %>_div").html(
  "<%= escape_javascript(
    render :partial => 'commontator/threads/show',
           :formats => [:html],
           :locals => { :thread => thread,
                        :user => user,
                        :page => page,
                        :per_page => per_page,
                        :show_all => show_all }) %>");

app/views/commontator/threads/show.js.erb
<%= render :partial => 'show',
           :locals => { :thread => @thread,
                        :user => @user,
                        :page => @commontator_page,
                        :per_page => @commontator_per_page,
                        :show_all => @show_all } %>

<%= javascript_proc %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">

<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>


    </button>
    <%= link_to "Hello Iran", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>


      <li><%= link_to raw('<span class="glyphicon glyphicon-plus-sign"></span>'), new_pin_path %></li>

      <% end %>



      <li><%= link_to raw('<span class="glyphicon glyphicon-book"></span>'), story_path %></li>



      <li><%= link_to raw('<span class="glyphicon glyphicon-camera"></span>'), pins_path %></li>

      <li><%= link_to raw('<span class="glyphicon glyphicon-info-sign"></span>'), about_path %></li> 

      <% if user_signed_in? %>
        <li><%= link_to raw('<span class="glyphicon glyphicon-cog"></span>'), edit_user_registration_path %></li>
        <li><%= link_to raw('<span class="glyphicon glyphicon-off"></span>'), destroy_user_session_path, method: :delete %></li> 
        <% else %>
        <li><%= link_to raw('<span class="glyphicon glyphicon-hand-up"></span>'), new_user_session_path %></li> 
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/pages/quotes.html.erb
<p>“In Persia first arises that light which shines itself and illuminates what is around...The principle of development begins with the history of Persia; this constitutes therefore the beginning of history” (Hegel, 1857, p. 147). </p>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">

    <%= link_to image_tag(pin.image.url(:medium)), pin %>

    <div class="panel-body">
      <%= pin.description %><br/>

      <strong><%= pin.user.name if pin.user %></strong>
      <% if pin.user == current_user %>

        <div class="actions">

        <%= link_to raw('<button><span class="glyphicon glyphicon-pencil"></span></button>'), edit_pin_path(pin) %>
        <%= link_to raw('<button><span class="glyphicon glyphicon-trash"></span></button>'), pin, method: :delete, data: { confirm: 'Are you sure?' } %>

      </div>

      <% end %>
      <%= commontator_thread(pin) %>

    </div>
    </div>
    <% end %>
    </div>

<div class="center">
<%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/show.html.erb
<%= link_to raw('<button>Back</button>'), pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">

        <%= image_tag @pin.image.url %>

      </div>

      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>

        <% if @pin.user == current_user %>
        
          <%= link_to raw('<button><span class="glyphicon glyphicon-pencil"></span></button>'), edit_pin_path(@pin) %>
          <%= link_to raw('<button><span class="glyphicon glyphicon-trash"></span></button>'), @pin, method: :delete, data: { confirm: 'Are you sure?' } %>

          <%= commontator_thread(@pin) %>
        
        <% end %>

      </div>
    </div>
  </div>
</div>